name: Code Coverage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'

      - name: Install Node.js dependencies
        run: npm install

      - name: Install global dependencies (if needed)
        run: npm install -g react-test-renderer

      - name: Run tests and generate code coverage
        run: npm test --coverage

      - name: Create coverage directory
        run: mkdir -p coverage

      - name: Copy coverage report to directory
        run: cp -r ./coverage/lcov-report/* coverage/

      - name: Publish code coverage to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage
