name: Code Coverage

on:
  push:
    branches:
      - main # Modify this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Adjust to your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run tests and generate code coverage
        run: npm test -- --coverage

      - name: Publish code coverage to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage/lcov-report
